###
POST https://{{host}}/api/user/changePassword
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{sessionId}}

{"data": {"passwordCurrent": "test", "passwordNew": "test"}}

###
POST https://{{host}}/api/user/current
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{sessionId}}

{"data": {}}

###
POST https://{{host}}/api/user/list
Accept: application/json
Content-Type: application/json

{"data": {}}

###
POST https://{{host}}/api/user/sign/in
Accept: application/json
Content-Type: application/json

{"data": {"user": "cust", "password": "test"}}

###
POST https://{{host}}/api/user/sign/out
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{sessionId}}

{"data": {}}


###
POST https://{{host}}/api/user/sign/up
Accept: application/json
Content-Type: application/json

{
  "data": {
    "email": "alex@flancer64.com", "login": "alex", "name": "Alex Gusev",
    "password": "LetMeIn", "phone": "29181801"
  }
}

###
